apiVersion: v1
kind: Pod
metadata:
  name: resources
  labels:
   name: resources-labels
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests: 
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
#limits should be either same or more than requests.