apiVersion: v1
kind: Pod
metadata:
 name: pod-using-configmap
spec:
  containers:
   - name: nginx
     image: nginx
     envFrom:
     - configMapRef:
        name: expense  #it refers the complete configmap file expense

    #  env:
    #  - name: course-details
    #    valueFrom: 
    #     configMapKeyRef:   #mentioning that values are referred from configmap
    #       name: expense
    #       key: course
    #  - name: duration-details
    #    valueFrom:
    #     configMapKeyRef:
    #       name: expense
    #       key: Duration 