apiVersion: v1
kind: Pod
metadata:
 name: pod-using-secrets
spec:
  containers:
   - name: nginx
     image: nginx
     envFrom:
     - secretRef:
        name: secrets  #it refers the complete configmap file expense