apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
    component: frontend
  #these labels belong to replica set resource
spec:
  replicas: 3 #specify no. of pods, as per our requirement
  selector:
    matchLabels:
      component: frontend
      app: nginx
    #below mentioned code refers to pod definition
  template:
    metadata:
      labels:
        component: frontend
        app: nginx
        project: expense
    spec:
      containers:
      - name: nginx
        image: nginx