apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: project
            operator: In
            values:
            - expense
  containers:
  - name: with-node-affinity
    image: nginx
  tolerations:                  #tolerations should match with the taint specs of node
  - key: "project"
    operator: "Equal"
    value: "expense"
    effect: "NoSchedule"