kind: ConfigMap
apiVersion: v1
metadata:
 name: filebeat
data: 
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
        - module: nginx
          access:
            var.paths: ["/path/to/log/nginx/access.log*"]
          error:
            var.paths: ["/path/to/log/nginx/error.log*"]
      output:
        elasticsearch:
          hosts: [ "elasticsearch:9200" ]
---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx/
  - name: filebeat
    image: docker.elastic.co/beats/filebeat:7.5.0
    volumeMounts:
    - mountPath: /usr/share/filebeat/filebeat.yml
      subPath: filebeat.yml
    - name: nginx-logs
      mountPath: /var/log/nginx/
  volumes:
  - name: nginx-logs
    emptyDir: {}
  - name: filebeat-config
    configMap:
      name: filebeat
      items:
        - key: filebeat.yml
          value: filebeat.yml