#defining the resource PVC, which is nothing but, claiming the required storage from earlier defined PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-claim
spec:
  storageClassName: "expense-ebs" # sc name is given
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
#defining the pod definition which acan use this PVC to vonnect to and use it
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    project: web
    component: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html/
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic-claim
# ---
# #load balancer service is used to test the above one
# apiVersion: v1
# kind: Service
# metadata: 
#   name: nginx-lb
# spec:
#   type: LoadBalancer
#   selector:
#     project: web
#     component: nginx
#   ports:
#     - protocol: TCP
#       port: 80   #service port
#       targetPort: 80  #pod port
      