#creating pv for the corresponding EFS of our project
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "fs-0f227f791178c5ebf"  #volume id of our EFS
---
# creating pvc for the above pv
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: "efs-pv"
  resources:
    requests:
      storage: 2Gi
---
#defining pod to use pvc
apiVersion: v1
kind: Pod
metadata:
  name: efs-pod
  labels:
    project: web
    component: nginx
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-static-claim
---
#load balancer service is used to test the above one
apiVersion: v1
kind: Service
metadata: 
  name: efs-static-lb
spec:
  type: LoadBalancer
  selector:
    project: web
    component: nginx
  ports:
    - protocol: TCP
      port: 80   #service port
      targetPort: 80  #pod port