#creating pvc for efs dynamic provisioning
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dynamic-sc
  resources:
    requests:
      storage: 5Gi
---
#defining pod to attach to EFS volume
apiVersion: v1
kind: Pod
metadata:
  name: efs-app
  labels:
    project: web
    component: nginx
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-dynamic-claim
---
#service is used to test the above one
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
spec:
  selector:
    project: web
    component: nginx
  ports:
    - protocol: TCP
      port: 80   #service port
      targetPort: 80  #pod port