kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0f11005d3cc24dfca  #EFS volume id should be given
  directoryPerms: "700"
  basePath: "/expense" #our project path i.e., creating a separate folder for our project in the EFS volume